### ISSUE TITLE
Webpacker3.4.3, Rails5.2 deployed to Heroku: /app/public/packs not available

### ISSUE THREAD

**Issue by yannis** [rails/webpacker#1452] opened 2018-04-26 11:20 UTC
Hi,
I've recently upgraded my app to Rails5.2 and Webpacker3.4.3.
Everything works fine in Development but when I deploy the app to Heroku, I get:

```
Reporting exception: Webpacker can't find vendor.js in /app/public/packs/manifest.json. Possible causes: 
1. You want to set webpacker.yml value of compile to true for your environment 
   unless you are using the `webpack -w` or the webpack-dev-server. 
2. webpack has not yet re-run to reflect updates. 
3. You have misconfigured Webpacker's config/webpacker.yml file. 
4. Your webpack configuration is not creating a manifest. 
Your manifest contains: 
{ 
} 
```

And indeed, when I list the content of `/app/public` I get:

```
~ $ ls public/
404.html  422.html  500.html  apple-touch-icon.png  apple-touch-icon-precomposed.png  assets  favicon.ico  maintenance.html  packs-test
```

`packs-test` is present but not `packs` despite the fact that the build logs show it as generated:

```
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       yarn install v1.5.1
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       info fsevents@1.2.2: The platform "linux" is incompatible with this module.
       info "fsevents@1.2.2" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       warning "@rails/webpacker > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
       warning " > coffee-loader@0.8.0" has unmet peer dependency "coffeescript@>= 1.8.x".
       [4/4] Building fresh packages...
       success Saved lockfile.
       Done in 27.70s.
       Webpacker is installed 🎉 🍰
       Using /tmp/build_9f98c4fa428950bf12a56624bfa429ec/config/webpacker.yml file for setting up webpack paths
       Compiling…
       Compiled all packs in /tmp/build_9f98c4fa428950bf12a56624bfa429ec/public/packs
       Asset precompilation completed (115.81s)
       Cleaning assets
       Running: rake assets:clean
```

Here's my `/config/webpacker.yml`

```
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  extensions:
    - .jsx
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/


test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true

```

and `/config/webpack/environment.js`

```
const { environment } = require('@rails/webpacker')

module.exports = environment
```

and `/config/webpack/production.js`

```
process.env.NODE_ENV = process.env.NODE_ENV || 'production'

const environment = require('./environment')

module.exports = environment.toWebpackConfig()
```

and `/config/webpack/test.js`

```
process.env.NODE_ENV = process.env.NODE_ENV || 'development'

const environment = require('./environment')

module.exports = environment.toWebpackConfig()
```

It seems that my webpack assets are somehow compiled in `public/packs-test` instead of  `public/packs` during deploy.

If I change `/config/webpacker.yml` test configuration from `public_output_path: packs-test` to `public_output_path: packs` everything works fine.

Any help with this would be greatly appreciated as I'm struggling with this for quite some times.
Let me know if you need more details.

**Comment by jeffbax** [comment] 2018-05-03 19:09
I'm seeing something similar since upgrading from 3.2.1, though on Heroku CI.

Effectively, it seems like the `RAILS_ENV=test` is causing CI to compile out to `packs-test` (seems reasonable given the defaults in `webpacker.yml`), but given `NODE_ENV=production` (or development) it doesn't seem to be resolving that directory properly. 

The build output saying it was sent to `packs`

```
Webpacker is installed 🎉 🍰
Using /app/config/webpacker.yml file for setting up webpack paths
Compiling…
Compiled all packs in /app/public/packs
-----> test-setup command `bundle exec rake assets:precompile` completed successfully
```

But the resulting files are
```
~/public $ ls
422.html  assets  favicon.ico  images  packs-test  vendors
```

and as a result the `rspec` tests encounter errors like this

```
Failure/Error: <%= javascript_pack_tag "manifest", defer: true %>
ActionView::Template::Error:
Webpacker can't find manifest.js in /app/public/packs/manifest.json. Possible causes:
```

I would expect the `javascript_pack_tag` to be resolving to `packs-test` in this case and be ok rather than `packs` given the webpacker.yml config, but am not sure if my assumptions are correct.

In the meantime, I will give just outputting to the standard folder to get around it until I have some more time to dig into things (since I don't particularly care about packs-test all that much, and if it overrides things locally, I can deal)

**Comment by yannis** [comment] 2018-05-03 21:50
In my case, I can fix this issue in production simply by commenting out
```
test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test
```

**Comment by gauravtiwari** [comment] 2018-05-04 08:27
Just pushed an example here: https://github.com/gauravtiwari/webpacker-example-latest and https://webpacker-example-latest.herokuapp.com/

I can't reproduce this issue on Heroku with latest webpacker. Could you please verify both gem and npm package are using the same version?

**Comment by gauravtiwari** [comment] 2018-12-15 14:05
Please try the latest RC, otherwise feel free to open a new issue with more details.

**Closed by gauravtiwari** 2018-12-15 14:05 UTC
