### ISSUE TITLE
Default .gitignore ignores precompiled packs leading to broken production react apps

### ISSUE THREAD

**Issue by amingilani** [rails/webpacker#534] opened 2017-06-25 10:32 UTC
Cross posted from https://github.com/rails/rails/issues/29564

> ### Steps to reproduce
> 
> * Create a new rails app with the `webpack=react` flag
> * Create a react component (e,g, `sales.jsx`) and mount onto a view
> * Precompile assets `rails assets:precompile`
> * Deploy to production
> * Open in production
> 
> ### Expected behavior
> 
> The app should run fine as in development
> 
> ### Actual behavior
> 
> The app breaks with the following error
> 
> ```
> 2017-06-22T05:15:05.148829+00:00 app[web.1]: F, [2017-06-22T05:15:05.148717 #4] FATAL -- : [ef509b29-8637-41b3-8224-4423dbf2b2ed]
> 2017-06-22T05:15:05.148948+00:00 app[web.1]: F, [2017-06-22T05:15:05.148883 #4] FATAL -- : [ef509b29-8637-41b3-8224-4423dbf2b2ed] ActionView::Template::Error (Can't find sales.js in /app/public/packs/manifest.json. Is webpack still compiling?):
> 2017-06-22T05:15:05.149203+00:00 app[web.1]: F, [2017-06-22T05:15:05.149103 #4] FATAL -- : [ef509b29-8637-41b3-8224-4423dbf2b2ed]     1: %div#sale
> 2017-06-22T05:15:05.149206+00:00 app[web.1]: [ef509b29-8637-41b3-8224-4423dbf2b2ed]     2: = javascript_pack_tag 'sales'
> 2017-06-22T05:15:05.149297+00:00 app[web.1]: F, [2017-06-22T05:15:05.149231 #4] FATAL -- : [ef509b29-8637-41b3-8224-4423dbf2b2ed]
> 2017-06-22T05:15:05.149398+00:00 app[web.1]: F, [2017-06-22T05:15:05.149328 #4] FATAL -- : [ef509b29-8637-41b3-8224-4423dbf2b2ed] app/views/sales/new.html.haml:2:in `_app_views_sales_new_html_haml___2340659139987297731_36903000'
> 2017-06-22T05:15:07.004434+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=planetlauncher.herokuapp.com request_id=8bca0b65-0d4a-494f-88c7-a4b31c2ff6dc fwd="202.163.79.6" dyno=web.1 connect=1ms service=2ms status=200 bytes=143 protocol=https
> ```
> 
> ### Recommended Fix
> 
> Update `.gitignore`
> 
> ```
> -- /public/packs
> ```
> 
> Allowing `/public/assets` to be committed but making `/public/packs` gitignored creates an awkward initial scaffold where you're kinda allowing precompilations to be committed, but not entirely.
> 
> ### System configuration
> 
> ```
> $ ruby -v
> ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
> $ rails -v
> Rails 5.1.1
> ```

**Comment by rafaelfranca** [comment] 2017-06-26 22:39
We don't want `public/packs` neither `public/assets` to be committed by default. They should be generated in the production machines not in the development machines. That being said, this is not a bug. If something needs to change is to add `public/assets` in the gitignore.

**Closed by rafaelfranca** 2017-06-26 22:39 UTC

**Comment by amingilani** [comment] 2017-06-26 22:57
Either way is fine by me as long as one of the stances is affirmed. The .gitignore intention is ambiguous.

**Comment by rafaelfranca** [comment] 2017-06-26 23:02
Yeah, agree. Could you open a PR to add `public/assets` on the gitignore in `rails/rails`?

**Comment by moalamin** [comment] 2018-11-08 16:58
> We don't want `public/packs` neither `public/assets` to be committed by default. They should be generated in the production machines not in the development machines. That being said, this is not a bug. If something needs to change is to add `public/assets` in the gitignore.

Hello, sorry I'm late but running into this issue now on a Rails 4.2 app. We precompile all our assets and serve them from our production machines. I'm a little confused as to why compiled packs generated w/ assets:precompile shouldn't be saved as part of the app? Can you explain how I can approach serving my assets so that the production machines are the ones generating my compiled packs?

Any explanations are appreciated, thank you!
