### ISSUE TITLE
bin/webpack-dev-server results in Cannot find module 'webpack-cli/bin/config-yargs'

### ISSUE THREAD

**Issue by olivierlacan** [rails/webpacker#1295] opened 2018-02-26 07:59 UTC
On a fresh Rails 5.1.5 app with Ruby 2.5.0 and Node 9.5.0, running `bin/webpack-dev-server` results in:

```
$ ./bin/webpack-dev-server
The CLI moved into a separate package: webpack-cli.
Please install 'webpack-cli' in addition to webpack itself to use the CLI.
-> When using npm: npm install webpack-cli -D
-> When using yarn: yarn add webpack-cli -D
module.js:557
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (.../appname/node_modules/webpack-dev-server/bin/webpack-dev-server.js:64:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
````

The suggested fix — `yarn add webpack-cli -D` — works. It seems like webpack-cli should be part of the default `packages.json` installed by Webpacker.

```
"devDependencies": {
    "webpack-cli": "^2.0.9",
    "webpack-dev-server": "^3.0.0"
  }
```

**Comment by gauravtiwari** [comment] 2018-02-26 11:16
@olivierlacan Thanks for filing the issue. It seems like dev server 3.0.0 doesn't work with older versions of webpack - https://github.com/webpack/webpack-dev-server/releases 

We need to update webpacker so it supports webpack v4.

**Comment by ssthil** [comment] 2018-02-27 11:20
In webpack 4.0.1 we need to run `yarn add webpack-cli -D` and it works!!!

**Comment by icechenfei** [comment] 2018-02-28 06:50
I add webpack-cli, and then run `npx webpack src/index.js dist/bundle.js --mode=development`. It's not work. but it's not tell me the reason

**Comment by ssthil** [comment] 2018-02-28 13:00
@icechenfei First add `npx webpack-cli` and then run `npm run start`. In your package.json add `"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server"
  }`

**Comment by inferusvv** [comment] 2018-03-02 15:11
> In webpack 4.0.1 we need to run yarn add webpack-cli -D and it works!!!
Why it is not in docs?

**Comment by gauravtiwari** [comment] 2018-03-03 14:18
Webpacker doesn't support/ship with webpack 4.0 at the moment. Will update docs once this is done.

**Comment by audiodude** [comment] 2018-03-04 20:51
I think this is broken, because the package.json that comes with a fresh install gives me:

```
  "devDependencies": {
    "webpack-dev-server": "^3.1.0"
  }
```

But meanwhile, webpack-dev-server from 3.0.0 on claims that:

> Breaking change: webpack v4 is now supported. Older versions of webpack are not supported.

https://github.com/webpack/webpack-dev-server/releases/tag/v3.0.0

**Comment by yunixon** [comment] 2018-03-06 10:55
> EDIT: Doing yarn install webpack-dev-server@^2 fixed it for me.

error `install` has been replaced with `add` to add new dependencies. Run "yarn add webpack-dev-server@^2" instead.

**Comment by richjdsmith** [comment] 2018-03-09 12:12
Running `yarn add webpack-dev-server@^2` led to the following not found:

> no matches found: webpack-dev-server@^2

Suggestions?

**Comment by gauravtiwari** [comment] 2018-03-09 12:46
Please run: `yarn add webpack-dev-server@^2.11.1`

**Comment by gauravtiwari** [comment] 2018-03-20 17:34
This is fixed with latest release, using 2.x until we upgrade to webpack 4.0.

**Closed by gauravtiwari** 2018-03-20 17:34 UTC

**Comment by tuteurprive** [comment] 2018-03-30 11:25
Hi guys,

I am totally new in coding, i started 1 month ago.

I have the following problem : my website does not work when i launch it locally. But it works when pushing on github and the staging.

When I type "yarn run dev" in my terminal, i . have the following : 

**Error: Cannot find module 'webpack/bin/config-yargs'                                                           
    at Function.Module._resolveFilename (module.js:555:15)                                                     
    at Function.Module._load (module.js:482:25)                                                                
    at Module.require (module.js:604:17)                                                                       
    at require (internal/module.js:11:18)                                                                      
    at Object.<anonymous> (/Users/francoisfourmentin/Code/application/node_modules/webpack-dev-server/bin/webpa
ck-dev-server.js:54:1)                                                                                         
    at Module._compile (module.js:660:30)                                                                      
    at Object.Module._extensions..js (module.js:671:10)                                                        
    at Module.load (module.js:573:32)                                                                          
    at tryModuleLoad (module.js:513:12)                                                                        
    at Function.Module._load (module.js:505:3)                                                                 
error Command failed with exit code 1.                                                                         
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.** 

I don't think it is a problem with webpack-cli but webpack.

In the end, when I launch on localhost:3000, the website does not appear.

Do you have an idea how to proceed ?

Thank you !

**Comment by ytbryan** [comment] 2018-03-30 11:42
Hi @tuteurprive, welcome!

You may be assuming that Rails works the same way as Node projects. But Rails is slightly different in a better way. Here is an incomplete checklist: 

0. Do you have `gem "webpacker"` at your Gemfile?
1. At your route.rb, do you have a root?
```
root "pages#index"
```
2. At your root page, in this case, `app/views/pages/index.html.erb`, do you have `<%= javascript_packs_tag "something"%>`
3. If 1 +2 are ok, then run `rails server` to get the Rails server running. note: it's not yarn run dev. 

Visit http://localhost:3000 and you should have something working. 

---
Alternatively, start a fresh project by typing these at your terminal. 
```
rails new app --webpack=vue
rails g scaffold pages
rails db:migrate
```
At `app/views/pages/index.html.erb`
replace all the text with `<%= javascript_packs_tag "hello_vue" %>`

At route.rb, make sure you have this.
```
root "pages#index" 
```

Run `rails server` and visit http://localhost:3000

Let me know if it works

**Comment by tuteurprive** [comment] 2018-04-02 11:18
hello ytbryan !

Many thanks for your help ! It's really reassuring to see that one can get such precise help !
I have followed your suggestions (together with a friend of mine who is lot more experienced in coding) and it worked. I think webpacker was not properly installed / working !

Many thanks, problem solved !

Best !

**Comment by ytbryan** [comment] 2018-04-02 11:22
No problem! Happy to help :)

**Comment by maddy65** [comment] 2018-06-04 13:01
Do we have any solution for lower version of webpack. I am using this webpack and it is failing for me. 

 `"webpack": "^4.10.2",
    "webpack-dev-server": "^3.1.4"`

**Comment by gauravtiwari** [comment] 2018-06-04 13:04
What version of webpacker are you using? This issue is fixed in latest 3.x version (3.5.3) or if you want to use v4, please checkout the pre-release.

**Comment by maddy65** [comment] 2018-06-04 13:48
I downgraded my webpack version and working for me. I was using v4.

**Comment by wjdhamilton** [comment] 2018-06-18 13:30
Hello,

If I run ` yarn add webpack-dev-server@^2.11.1` I get the following error: `no matches found: webpack-dev-server@^2.11.1`. Can anyone help?

Many thanks

**Comment by wjdhamilton** [comment] 2018-06-25 13:33
@gauravtiwari thanks that fixed it!

**Comment by majioa** [comment] 2020-03-28 12:51
isn't work with added as development 

    "webpack": "^4.42.0",
    "webpack-cli": "^3.3.11"

**Comment by BuonOmo** [comment] 2021-01-07 10:24
I had the same issues, however, none of the above solutions worked. I ended up patching a bit the `DevServerRunner` to use the now standard `webpack serve` instead of `webpack-dev-server`:

```patch
diff --git a/lib/webpacker/dev_server_runner.rb b/lib/webpacker/dev_server_runner.rb
index be5557b..978c13a 100644
--- a/lib/webpacker/dev_server_runner.rb
+++ b/lib/webpacker/dev_server_runner.rb
@@ -66,9 +66,9 @@ module Webpacker
         env["WEBPACKER_CONFIG"] = @webpacker_config
 
         cmd = if node_modules_bin_exist?
-          ["#{@node_modules_bin_path}/webpack-dev-server"]
+          ["#{@node_modules_bin_path}/webpack", "serve"]
         else
-          ["yarn", "webpack-dev-server"]
+          ["yarn", "webpack", "serve"]
         end
 
         if @argv.include?("--debug-webpacker")
@@ -85,7 +85,7 @@ module Webpacker
       end
 
       def node_modules_bin_exist?
-        File.exist?("#{@node_modules_bin_path}/webpack-dev-server")
+        File.exist?("#{@node_modules_bin_path}/webpack")
       end
   end
 end
```

Works like a charm :)

**Comment by shaneajeffery** [comment] 2021-05-22 21:22
> ```diff
> webpack
> ```

Hey there boss.  Did you have to make any other changes to your setup?  I'm using:

```
"webpack": "5.37.1",
"webpack-dev-server": "3.11.2",
"webpack-cli": "4.7.0"
```

It keeps trying to find the `src` directory instead of using the configuration from the `webpack.yml` file whenever I do `webpack serve` now.

**Comment by BuonOmo** [comment] 2021-05-24 08:06
@shaneajeffery 

From my yarn.lock:

```
    webpack "^4.44.1"
    webpack-cli "^4.0.0"

webpack-dev-server@^3.11.0:
  version "3.11.0"
```

Hence we have very different versions, if you have an open-sourced [example app](https://www.codetriage.com/example_app) that fully reproduces the issue I'd be glad to help you on that 🙂
