### ISSUE TITLE
Process towards release (or "what's blocking Webpacker 6")?

### ISSUE THREAD

**Issue by wwahammy** [rails/webpacker#3055] opened 2021-06-16 21:47 UTC
First off, I love Webpacker a ton. It makes webpack ways easier to use with Rails and I'm thankful it exists.

I feel in the dark though about what the plan is for a Webpacker 6 release. I don't see it really documented or explained so I think the community in general would value some insight. I hear a lot of people saying the current betas are stable but it's not clear what the process is from here to Webpacker 6.

Any insight would be helpful for everyone's planning as well as allow the community to assist on fixing any remaining issues. After all, we can't fix any blocking bugs or add blocking features if we don't know what those features are!

Thanks again for everything the leaders in the community do and for everyone on their amazing work on Webpacker.

**Comment by t27duck** [comment] 2021-06-17 17:20
Was about to open an issue about something similar, but I think it would be in the best interests to go into a RC phase. Mainly due to people still getting bit by the "you want the latest? uh... the letters 'pre' come before 'beta' so this is probably the most recent version" of both yarn/npm and rubygems and ending up with the many months-old pre releases where nothing works.

**Comment by jaredbeck** [comment] 2021-06-17 21:31
See also https://github.com/rails/webpacker/issues/2999, "How stable is v6.0.0.beta.7"

**Comment by mattiagiuffrida-st** [comment] 2021-06-21 08:59
+1 on releasing a RC first as @t27duck suggested to fix the release semver order.
Any blocker before that could happen? Is there a roadmap on what still needs to be included / unfinished work before we can have a RC?

**Comment by Eusebius1920** [comment] 2021-06-21 13:47
I can't wait to Webpacker 6 to be released as stable - it will solve a ton of "problems". It is a really nice idea who it changes to a light webpack wrapper (with sensible out-of-the-box configuration for all-optional webpack-loaders / modules) with the new "modularity".

**Genius!**  :heart: 

Thanks to all the contributors so far.

**Comment by justin808** [comment] 2021-06-24 07:55
If anybody could try out and review https://github.com/rails/webpacker/pull/3031, that would be helpful!

Support for CSS modules with HMR seems essential.

**Comment by mattiagiuffrida-st** [comment] 2021-06-24 14:48
Sorry but I don't use webpacker for CSS files, only for JS. Hopefully someone will be able to test that soon

**Comment by swrobel** [comment] 2021-06-29 15:15
> If anybody could try out and review #3031, that would be helpful!
> 
> Support for CSS modules with HMR seems essential.

Thank you @justin808! Looks like this was just merged yesterday.

**Comment by Eusebius1920** [comment] 2021-06-29 16:42
would be a good opportunity to release a new (beta or release candidate) version of v6? (that fixes the `.pre`-version-schema problem)

**Comment by ahukkanen** [comment] 2021-07-06 13:29
This issue is really bothering. We just ended up spending ~2h debugging a dependency issue which was caused by webpacker dependency installing the `pre` version which is older than `beta` but higher in alphabetical order.

Or at least, consider yanking the `pre` releases which are causing dependency definitions such as `spec.add_dependency "webpacker", "~> 6.0.0.beta.7"` to install the `pre` version because it is the highest match for that dependency.

Or as suggested, release an RC version which would be higher than "pre".

**Comment by Eusebius1920** [comment] 2021-07-06 13:55
> This issue is really bothering. We just ended up spending ~2h debugging a dependency issue which was caused by webpacker dependency installing the `pre` version which is older than `beta` but higher in alphabetical order.

I have been at exactly this point, wasting time and thus begging for a new release that fixes this. 

This would be a good idea for a final release too. Since there might be many using the old `pre`-versions instead of testing the `beta` ones...

**Comment by Nittarab** [comment] 2021-07-08 15:00
There is something we can do to release a new beta? 
I'm using v6.0.0.beta.7 and is awesome, a lot of work is been made since the last release. I'm curious to test it.

I don't know who the maintainers of this repo, I think there are many people ready to help release a new version

**Comment by mattiagiuffrida-st** [comment] 2021-08-16 09:03
@justin808 sorry to chase again on this, but can we just get the [semver](https://rubygems.org/gems/webpacker/versions) fixed on Webpacker 6 releases?

I understand you may want to wrap things up before the final release (it would still be great to see a clear plan for that), but this is getting quite annoying and we might miss new betas because we have to fix the gem version in our Gemfiles.

If you don't want to make an RC release yet, just call it anything that is alphabetically bigger than `pre`, or just yank the `pre` releases, I don't mind either way 😄, but please just fix the [versioning](https://rubygems.org/gems/webpacker/versions)

**Comment by jaredbeck** [comment] 2021-08-16 15:42
Last week, DHH said that "Webpacker [is] no longer a good default for Rails". (["Modern web apps without JavaScript bundling or transpiling"](https://world.hey.com/dhh/modern-web-apps-without-javascript-bundling-or-transpiling-a20f2755))

> I'm grateful that tools like Webpack made this transition possible, though. Despite the complexity, it felt worth the bargain. So back in 2016, I created Webpacker, and in 2017, we shipped Rails 5.2, which embraced this approach to managing JavaScript with Rails.
>
> Five years later, the facts on the ground have finally changed. I no longer believe that this bargain is worth it for most new applications. It's not a dead-end, and there are still certain types of applications where it does make sense (hello react!), but it's no longer a good default for Rails.

We should be careful about drawing any conclusions about the fate of Webpacker from this one comment, but I thought it bore inclusion here.

**Comment by wwahammy** [comment] 2021-08-16 18:43
All, I posted on the Rails forum to move Webpacker forward (https://discuss.rubyonrails.org/t/current-state-of-webpacker/78685). If you're interested in Webpacker and the issues discussed her and on the post, please comment!

**Comment by justin808** [comment] 2021-08-17 04:51
> @justin808 sorry to chase again on this, but can we just get the [semver](https://rubygems.org/gems/webpacker/versions) fixed on Webpacker 6 releases?

I wish I could! 

See [https://discuss.rubyonrails.org/t/current-state-of-webpacker/78685/4?u=justin_gordon](Ruby on Rails Forum).

**Comment by mattiagiuffrida-st** [comment] 2021-08-17 08:27
Thanks for raising the versioning issue in the forum @justin808 and for offering help!
It sounds like Rafael might get this fixed this week 🙌 
I also totally agree with your suggestion about releasing a v6 of rails/webpacker now and then do a v7 with the next major Rails release ❤️ 

Will jump on the forum there to share that as well

**Comment by dhh** [comment] 2021-08-20 11:32
Webpacker 6.0.0.rc.1 has been released. Getting close!

**Closed by dhh** 2021-08-20 11:32 UTC

**Comment by mattiagiuffrida-st** [comment] 2021-08-20 13:39
Thanks for weighting in and moving this along @dhh, exciting to see the final release edging closer 🚀
