### ISSUE TITLE
Doesn't do .css if there's no .scss in javascript/packs

### ISSUE THREAD

**Issue by pitosalas** [rails/webpacker#1602] opened 2018-07-09 13:45 UTC
I'm very new at webpack but... I am having the following experience:

- running rails with Webpacker and Stimulus installed (I don't think stimulus has anything to do with the problem
- I put a minimal application.css file in javascript/packs. I run the server, and load a page and get an error because the output file for that  .css is not "compiled" and put into public/packs
- I add a minimal application.scss and now when I run the server I see BOTH the compiled output from the .scss and the .css files in public/packs

Does that make sense? Am I misunderstanding a key thing?

**Comment by gauravtiwari** [comment] 2018-07-09 13:59
@pitosalas Can't seem to reproduce this issue. You have to restart your server if you added anything to packs folder since that is main entries folder. Also, we don't recommend putting css or scss files directly intro packs folder: https://github.com/rails/webpacker#usage

> now when I run the server I see BOTH

What server are you using webpack dev server or on-demand compiler?

**Comment by pitosalas** [comment] 2018-07-10 13:53
I don't know if this is useful, but I also found that many things written in various places say/imply that you should have in your app/javascript/pack directory, two files, named application.js and application.scss. However it seems to me that having both of the files named application.* doesn't work because the compiler overwrites one with the other. I had to rename the second one to e.g. applicationstyles.scss.

**Comment by renchap** [comment] 2018-07-10 14:05
`app/javascript/pack` is for your pack files.
Each file here is added as an entrypoint (https://webpack.js.org/concepts/entry-points/) in Webpack config.

You should not have your `.scss` file here, only a few `.js` files. In those files, you can import your code.

For example:

```js
// in app/javascript/pack/application.js
import "../js/application.js";
import "../styles/application.scss";
```

**Comment by pitosalas** [comment] 2018-07-10 20:03
Ah! I could swear I saw examples of .css or .scss in ../pack.

The thing that's confusing is importing from within java an scss or css file. How does that work out?

Also in my case, the file in question is installed with yarn in /node_modules/bulma/css/bulma.css or in /node_modules/bulma/buma.sass. What's the right way to do that?

import "/node_modules/bulma/bulma.sass";?

**Comment by gauravtiwari** [comment] 2018-07-11 08:19
@pitosalas 

Sure. Lets say if we have structured our app like so:

```yml
app/javascript: 
  packs: # having single pack/per view helps serve isolated and less code in the browser
     - view1.js # import '../src/styles/view1.scss'
     - view2.js # import '../src/styles/view2.scss'
     - view3.js # import '../src/styles/view3.scss'
     - so on....
  src: 
     - components
     - images
     - styles 
       - shared
         - variables.scss
       - view1.scss # @import "~bulma/bulma.sass";
       - view2.scss # @import "./shared/variables.scss";
       - view3.css
     - etc. 
  test: 
```

```erb
<%= javascript_pack_tag 'view1' %>
<%= javascript_pack_tag 'view2' %>
<%= javascript_pack_tag 'view3' %>
```

You can also use this for relative imports: https://github.com/rails/webpacker/blob/8bcbfbce95773ca3f41b7c8314842a4a6f015cd8/docs/assets.md#using-babel-module-resolver

References: 
1. https://github.com/webpack-contrib/sass-loader#imports

**Comment by pitosalas** [comment] 2018-07-11 11:37
Great, thanks! It's a little confusing still with all the moving parts! So are you saying that all the packs files should be *.js and contain only imports? 

I see that I misread the hints for stimulus and that they say to put the application.js in src and I have it in packs! 

So even for stimulus, I would have a stim.js in packs with just one line, import ../src/application.js right?

**Comment by pitosalas** [comment] 2018-07-11 12:20
Thank you for your time. It’s been super helpful!

Pito Salas
Brandeis Computer Science
Volen 134

**Comment by gauravtiwari** [comment] 2018-07-11 13:13
Great, no problem. Okay to close the issue?

**Closed** 2018-07-11 22:30 UTC
