### ISSUE TITLE
Error messaging when running rake assets:precompile

### ISSUE THREAD

**Issue by djforth** [rails/webpacker#1677] opened 2018-08-30 09:30 UTC
When running rake assets:precompile if the compile has any issues you don't get any feedback or error messaging.

To give you a bit more info I had accidentally added a package to dev dependencies, so when I ran:

`NODE_ENV=production rake assets:precompile`

Because the compile step brings in fresh packages and if you specify NODE_ENV=production it won't include the devDependency (or doesn't seem too).  The compile was failing because the package couldn't be found. This is fine except the compile step just hung no errors just said compiling...
When I eventually tried: 

`NODE_ENV=production ./bin/webpack`

I realised what the issue was as all the error messages appeared.

What would be handy is if there are any errors in the compile it displays so you can pick up on them faster.

Also whether a way to disable fresh package import might be handy? I find if I compile locally for production I always have to re-install my dev packages. Something like:

`NODE_ENV=production rake assets:precompile --no-install`

Would be very handy.

**Comment by eliank** [comment] 2018-11-13 14:57
:+1: 
`Open3.capture3` captures all output, as expected, but since it doesn't return the output is never shown.  I patched https://github.com/rails/webpacker/blob/master/lib/webpacker/compiler.rb#L59 so it calls `Webpacker::Runner` inline instead of using open3. This made the errors visible/fixable for us.

**Comment by kirillian** [comment] 2019-07-07 16:23
This appears to be a bug, but an easy workaround (after MUCH searching for it) is to set the following key in your webpacker.yml:
```
webpack_compile_output: true
```

In my case, I was compiling assets for production, so it looked something akin to this:
```
production:
  <<: *default

  webpack_compile_output: true
```

**Comment by jakeNiemiec** [comment] 2019-07-08 17:31
Relavent line: https://github.com/rails/webpacker/blob/195396f1e6dd1cb94d4c12887ae40884a6c18505/lib/webpacker/compiler.rb#L79-L81

I think there should be more logging, but there is strong disagreement over how much logging should be shown by default: https://github.com/rails/webpacker/issues/955#issuecomment-499123464

**Comment by jebw** [comment] 2019-07-18 07:55
Underlying this is webpacker only reports stderr, on the assumption that webpack itself reports errors on stderr. Instead it reports (some ? all ?) errors on stdout.

Either webpack itself needs correcting to report errors on stderr, or the stdout content needs to be included in the logging since it may contain the errors.

**Comment by kirillian** [comment] 2019-07-18 14:23
This is a really good point. The mismatched expectations is the root cause. The workaround I provided took advantage of the fact that `stdout` is captured and just toggles it so that it shows...

The expectation here seems to be that errors show on stdout. Since that expectation is wrong, reevaluating the expectation seems logical to me.

**Comment by jackkinsella** [comment] 2019-08-15 06:58
Ran into this today. I had a broken config due to the unavailability of an import from `normalize-css`. Running webpacker as usual only returned `error Command failed with exit code 2.`

I then cross-referenced with running `webpack` pure, separating stderr and stdout:

`$ yarn run webpack --config config/webpack/production.js 1>stdout.log 2>stderr.log`

Sure enough, `stderr.log` only had one line of error — the same one as `webpacker`, whereas the `stdout.log` had a detailed and helpful stack-trace:

```
ERROR in ./app/webpacker/stylesheets/application.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Failed to find 'normalize-css/normalize.css'
....
```

I would have expected `webpack` to print these errors to `stderr`, but it doesn't. There is [talk about this over in their repo](https://github.com/webpack/webpack/issues/1278), specifically they mention other tools relying on `stderr`. This is an area to watch. 

I think they should change things, but if they don't I would expect webpacker's `compiler.rb` to parse stdout on non-zero exit codes and spit out the errors. We in the Rails community like our tools to be intuitive after all :)

**Comment by jakeNiemiec** [comment] 2019-08-15 18:11
@jackkinsella Can you check if the issue was fixed with  https://github.com/rails/webpacker/issues/2190

**Comment by jackkinsella** [comment] 2019-08-16 08:08
@jakeNiemiec Have confirmed — it's fixed on master/head. Awesome stuff!

**Closed** 2019-08-17 00:04 UTC

**Comment by JetForMe** [comment] 2022-11-17 07:47
I'm running into this on v4.0.2 while upgrading from v3.5.3
