### ISSUE TITLE
FrozenError: can't modify frozen Array when adding devServer middleware

### ISSUE THREAD

**Issue by mikker** [rails/webpacker#1700] opened 2018-09-14 09:38 UTC
I have no idea why but somehow, in one of my projects, `app.middleware.middlewares` is frozen when Webpacker tries to insert its devServer middleware.

I've _"fixed"_ it by `dup`ing the array (see https://github.com/rails/webpacker/compare/master...mikker:frozen-middlewares).

I've tried disable some gems and the like but haven't been able to find the culprit yet.

---

Ruby: 2.5.1
Rails: 5.2.1
Webpacker: 3.5.5 and/or `master`

**Comment by gauravtiwari** [comment] 2018-09-14 11:59
Hey @mikker 

Are you eager loading code in development?

```rb
  # Do not eager load code on boot.
  config.eager_load = false
```

**Comment by mikker** [comment] 2018-09-14 12:31
Nope, `config.eager_load = false`

**Comment by rossta** [comment] 2018-09-14 16:29
@mikker Any chance you're using ActiveAdmin `~> 1.4.1`? I've seen similar issues reported elsewhere with that being another common link. That release does some introspection in the app middleware that could be a root cause, though I wasn't able to reproduce the issue myself.

* rails/rails#33745
* sferik/rails_admin#3060
* rossta/serviceworker-rails#59

**Comment by vincentwoo** [comment] 2018-09-23 04:50
I'm also seeing this with RailsAdmin 1.4.1 but not 1.4.0. It seems likely this commit (https://github.com/sferik/rails_admin/commit/59478af9a05c76bdfe35e94e63c60ba89c27a483) is responsible, but I can't for the life of me figure out why.

**Comment by mshibuya** [comment] 2018-09-23 09:42
Sorry to bother you, RailsAdmin 1.4.2 is out with the fix for this:
https://github.com/sferik/rails_admin/commit/94928d1de7cf6fd01ee19ed7a94f17c91e19282d

**Closed** 2018-12-15 18:58 UTC

**Comment by marcelino056** [comment] 2019-03-18 05:23
Still having the same issue:

```
Completed 500 Internal Server Error in 3765ms (ActiveRecord: 278.3ms)
  
FrozenError (can't modify frozen fatal):
```

rails_admin (1.4.2)
ruby 2.5.5
rails 5.2.2
