### ISSUE TITLE
Manifest includes assets_url in v4.0.0.rc.2

### ISSUE THREAD

**Issue by JanStevens** [rails/webpacker#1845] opened 2018-12-20 08:54 UTC
Hello

In version `v4.0.0.rc.2` now generates a manifest.json file that includes the configured asset host

```json
{
  "admin.css": "https://xxxxx.cloudfront.net/packs/admin-e902804e.css",
}
```

In my production.rb I got

```ruby
config.action_controller.asset_host = "https://xxxxx.cloudfront.net"
```

And my environment.js has

```js
const splitChunks = {
  optimization: {
    runtimeChunk: false,
    splitChunks: {
      chunks: 'all'
    }
  }
}

environment.config.merge(splitChunks)

environment.plugins.insert(
  'Manifest',
  new WebpackAssetsManifest({
    integrity: false,
    entrypoints: true,
    writeToDisk: true,
    publicPath: true
  })
)
```

In version `v4.0.0.pre.3` the same settings would generate the manifest as followed:

```json
{
  "admin.css": "/packs/admin-e902804e.css",
}
```

I do want to turn this off, since I do not know during compilation of my assets the cloudfront url and my devops team might want to change the cloudfront url. This would now mean we have to recompile assets again.

We compile assets and upload them to S3 using

```bash
 env RAILS_ENV=production env NODE_ENV=production bundle exec rake webpacker:compile   
```

Regards

**Comment by gauravtiwari** [comment] 2018-12-20 10:58
Thanks for reporting, let me take a look 👍

**Comment by iggant** [comment] 2019-01-28 22:39
@gauravtiwari If this is not a bug, can you please explain why this happens, and can this will be fixed by any config parameter?

**Comment by marcohamersma** [comment] 2019-02-01 18:34
@gauravtiwari I think this is breaking stuff for our users. Just adding `wontfix` without any explanation is not very communicative.

**Comment by joelmoss** [comment] 2019-02-19 09:10
> Just adding `wontfix` without any explanation is not very communicative.

Extremely unhelpful, and not in the spirit of open source at all :(

**Comment by guilleiguaran** [comment] 2019-03-03 18:19
Please take a look to https://github.com/rails/webpacker/pull/1973

**Comment by gauravtiwari** [comment] 2019-03-03 18:28
Sorry about not adding more info earlier. I was away :)

Basically, this is not a bug, in other words, it sort of like chicken-egg situation. Rails add CDN host through helper tags for all the assets included in the views, however, assets like images or font icons which are included inside JS code or CSS files don't have CDN if we don't supply full public path since it's processed by file loader, which uses webpack public path. 

For example:

```js
import Rails from 'rails'
import Rails2 from 'rails_assets'
import Google from 'some_namespace/google'

const Hello = props => (
  <div>Hello {props.name}!<img src={Google} /> <img src={Rails} /> <img src={Rails2} /></div>
)
```

**Note:** The images included above won't have CDN included since they are processed by webpack using file loader.

Now, current implementation works for both cases, since Rails is intelligent enough to figure out that a URI includes CDN host if we supply a CDN host to webpack and the generated URI includes CDN host, Rails doesn't add CDN host to it and the embedded assets also include CDN hosts. 

I see, this might not be ideal for some cases like described above but this is the best we can get at the moment that's why I added won't fix label earlier. 

If anyone has ideas, feel free to post.

**Comment by gauravtiwari** [comment] 2019-03-03 18:38
Found a solution :)

**Comment by gauravtiwari** [comment] 2019-03-03 18:57
Please see the PR

**Closed** 2019-03-03 21:14 UTC
Labels: bug

**Comment by marcohamersma** [comment] 2019-03-04 11:27
Great! thanks for taking a look 🙂
