### ISSUE TITLE
Webpacker + DevServer + @webpack-cli/serve compatibility

### ISSUE THREAD

**Issue by gencer** [rails/webpacker#2854] opened 2021-01-01 00:58 UTC
Yesterday, Dependabot bumped our `@webpack-cli/*` packages to the `v1.2.1`. I discovered that, in development environment, if you start `webpack-dev-server`, `devServer` config parameters are not loaded. So, simply I tested with this in `development.js`

```javascript
// config/webpack/development.js
const { webpackConfig, merge } = require('@rails/webpacker')


console.log(process.env.WEBPACK_DEV_SERVER)
console.log(webpackConfig.devServer)
exit(1)
```

And output was:

```javascript
undefined
undefined
```

instead it should be `true` and second one should include `devServer` properties. So, I have downgraded `@webpack-cli/info` to `v1.2.0` and tested again. Not worked. Then, I downgraded `@webpack-cli/serve` to `v1.2.0` and voala, thats worked.

I couldn't properly find the exact source but after upgrading `@webpack-cli/serve` to `v1.2.1`, `devServer` options are not merged with webpack config on development because `WEBPACK_DEV_SERVER` is `undefined` and therefore, your script does not inject server properties to the final config.

I don't know If this should be reflected to this package or should be fixed there, so im first opening an issue here.

Let me know what you think and I will forward/move this issue if it is irrelevant against here.

**Note**: I am using Webpacker 6.0.0.beta.2. I think this also affects older versions too, but not tested.

**Comment by LeBenLeBen** [comment] 2021-01-02 12:21
I have the same issue and downgrading `@webpack-cli/serve` to 1.2.0 work around the issue for me too. For others that would come across this, you can fix the version using yarn `resolutions` field in the `package.json`:

```json
  "resolutions": {
    "@webpack-cli/serve": "1.2.0"
  },
```

**Comment by apuntovanini** [comment] 2021-01-02 13:17
@LeBenLeBen @gencer Thanks, finally solved after so much time lost on it!

**Comment by gencer** [comment] 2021-01-02 15:38
Another option would be to use latest version and add this line at the top of `development.js`:

```javascript
process.env.NODE_ENV = process.env.NODE_ENV || 'development'
process.env.WEBPACK_DEV_SERVER = process.env.WEBPACK_DEV_SERVER || true // <-- this line
```

This will trigger webpack-dev-server in the background. However, at CI/CD stage this may be cause some unwanted behaviors. So, I believe downgrading is the safest solution at the moment.

Thanks @LeBenLeBen for `resolutions`

**Comment by gauravtiwari** [comment] 2021-01-04 14:45
Thanks, all for updates. Will take a look

**Comment by pedrofurtado** [comment] 2021-01-20 20:24
Hey guys! This PR resolve this issue? https://github.com/rails/webpacker/pull/2898

It are already merged in repo.

**Comment by gencer** [comment] 2021-01-31 21:57
@pedrofurtado Nope. Not in my case.

```javascript
console.log(process.env.WEBPACK_DEV_SERVER)
console.log(webpackConfig.devServer)
exit(0)

# Output:

undefined
undefined
```

Installed packages:

```yaml
@webpack-cli/serve: 1.2.2
@webpack-cli/info: 1.2.1
@rails/webpacker: 6.0.0-beta.4
```

**Comment by arusa** [comment] 2021-02-21 09:03
I can confirm this problem after updating rails/webpacker from 4 to 6.

webpack-dev-server always starts running at http://localhost:8080/ instead of the configured 0.0.0.0:3035

Also I am really wondering why the CLI params --host and --port are being explicitly disallowed in https://github.com/rails/webpacker/blob/master/lib/webpacker/dev_server_runner.rb
Because using them directly on `/app/node_modules/.bin/webpack serve` works fine.

installed package versions:
```
gem: webpacker (6.0.0.pre.2)

webpack-cli: 4.5.0
@webpack-cli/serve: 1.3.0
@webpack-cli/info: 1.2.2
@rails/webpacker: 6.0.0-beta.5
```

config/webpack/base.js:
```
const { webpackConfig } = require('@rails/webpacker')

module.exports = webpackConfig
```

config/webpack/development.js:
```
process.env.NODE_ENV = process.env.NODE_ENV || 'development'

const webpackConfig = require('./base')
console.log(webpackConfig)
module.exports = webpackConfig
```

output of the command bin/webpack-dev-server would start (/app/node_modules/.bin/webpack serve --config /app/config/webpack/development.js):
```
{
  mode: 'development',
  output: {
    filename: 'js/[name]-[contenthash].js',
    chunkFilename: 'js/[name]-[contenthash].chunk.js',
    hotUpdateChunkFilename: 'js/[id]-[hash].hot-update.js',
    path: '/app/public/packs',
    publicPath: '/packs/'
  },
  entry: {
    application: [
      '/app/app/packs/entrypoints/application.js',
      '/app/app/packs/entrypoints/application.scss'
    ]
  },
  resolve: {
    extensions: [
      '.js',   '.jsx',
      '.mjs',  '.ts',
      '.tsx',  '.coffee',
      '.scss'
    ],
    modules: [ '/app/app/packs', 'node_modules' ],
    plugins: [ [Object] ]
  },
  plugins: [
    EnvironmentPlugin { keys: [Array], defaultValues: [Object] },
    CaseSensitivePathsPlugin {
      options: {},
      logger: [Object [console]],
      pathCache: {},
      fsOperations: 0,
      primed: false
    },
    WebpackAssetsManifest {
      hooks: [Object],
      options: [Object],
      assets: [Object: null prototype] {},
      assetNames: Map {},
      currentAsset: null,
      compiler: null,
      hmrRegex: null,
      [Symbol(isMerging)]: false
    },
    MiniCssExtractPlugin {
      _sortedModulesCache: [WeakMap],
      options: [Object],
      runtimeOptions: [Object]
    }
  ],
  resolveLoader: { modules: [ 'node_modules' ], plugins: [ [Object] ] },
  optimization: { splitChunks: { chunks: 'all' }, runtimeChunk: 'single' },
  module: {
    strictExportPresence: true,
    rules: [ [Object], [Object], [Object], [Object], [Object] ]
  },
  devtool: 'cheap-module-source-map'
}
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /packs/
ℹ ｢wds｣: Content not from webpack is served from /app
```

It looks like webpack-dev-server does not interpret or read config/webpack.yml

**Comment by arusa** [comment] 2021-02-21 09:05
Immediately after writing this I found the solution/workaround for me.

If I manually set these two env vars everything runs fine:

```
WEBPACKER_CONFIG=/app/config/webpacker.yml
WEBPACK_DEV_SERVER=true
```

They should be set here: https://github.com/rails/webpacker/blob/b7069f4618de51415a4449908346a3c0853880dc/lib/webpacker/dev_server_runner.rb#L66

But somehow there seems to be a problem with setting the environment when running `webpack serve`:

```
Kernel.exec env, *cmd
```

**Comment by arusa** [comment] 2021-02-21 09:21
Ok, finally could figure it out completely. The problem is, that this line is missing in my version of rails/webpacker:
https://github.com/rails/webpacker/blob/b7069f4618de51415a4449908346a3c0853880dc/lib/webpacker/dev_server_runner.rb#L67

And it was added 1 month ago as a workaround:
https://github.com/rails/webpacker/commit/f56f8adf21a0238b9102cb6e4a20e7e18f5d3f28

Which was already mentioned above:
https://github.com/rails/webpacker/issues/2854#issuecomment-763910090

So the workaround seems to be to do one of these steps:

- use rails/webpacker gem from master branch
- set environment variable WEBPACK_DEV_SERVER="true" before running webpack-dev-server

**Comment by Mange** [comment] 2021-04-01 13:44
It's strange, because `devServer` is populated with the config:

```js
const { webpackConfig, devServer } = require(…);

console.log(webpackConfig.devServer); // undefined
console.log(devServer); // undefined
```

If I try to manually merge it, then I get an error:

```js
module.exports = merge(webpackConfig, {devServer: devServer});
```

```
[webpack-cli] webpack Dev Server Invalid Options

options should NOT have additional properties
options should NOT have additional properties
options should NOT have additional properties
options should NOT have additional properties
options should NOT have additional properties
options should NOT have additional properties
```

This stopped me in my tracks while trying to upgrade to Webpacker 6.

**Comment by zedtux** [comment] 2021-12-16 19:38
So, I tried @LeBenLeBen [solution](https://github.com/rails/webpacker/issues/2854#issuecomment-753467279) but I'm facing the following error:

```
webpack_1             | [webpack-cli] Unable to load '@webpack-cli/serve' command
webpack_1             | [webpack-cli] TypeError: Cannot read property 'getPkg' of undefined
webpack_1             |     at ServeCommand.apply (/application/node_modules/@webpack-cli/serve/lib/index.js:10:38)
webpack_1             |     at loadCommandByName (/application/node_modules/webpack-cli/lib/webpack-cli.js:1113:25)
webpack_1             |     at async Command.<anonymous> (/application/node_modules/webpack-cli/lib/webpack-cli.js:1641:9)
webpack_1             |     at async Promise.all (index 0)
webpack_1             |     at async WebpackCLI.run (/application/node_modules/webpack-cli/lib/webpack-cli.js:1677:5)
webpack_1             |     at async runCLI (/application/node_modules/webpack-cli/lib/bootstrap.js:8:5)
```

I also tried @arusa [solution](https://github.com/rails/webpacker/issues/2854#issuecomment-782825747) but it fails with:

```
webpack_1             | [webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
webpack_1             |  - options has an unknown property 'watchOptions'. These properties are valid:
webpack_1             |    object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, static?, watchFiles?, webSocketServer? }
```

Is there anything else to try?

**Comment by justin808** [comment] 2021-12-17 09:16
Seems like you have to update some dependencies. 

WEBPACK_DEV_SERVER changed to WEBPACK_DEV_SERVE

**Comment by justin808** [comment] 2021-12-17 09:34
You're definitely missing something, or if you find something, please update the upgrade doc.

**Closed by justin808** 2021-12-17 09:34 UTC

**Comment by zedtux** [comment] 2021-12-17 09:35
I see, so I guess that means I should wait for the version 6 to be stable. Thanks ..
