### ISSUE TITLE
Files in packs directory must have unique base file names

### ISSUE THREAD

**Issue by levinmr** [rails/webpacker#2096] opened 2019-05-20 19:34 UTC
Webpacker does not correctly create the manifest.json content if multiple files in the packs directory have the same basename (i.e. `application.*`)

Steps to reproduce:

- Create a new rails app with webpacker
- Add `/app/javascript/packs/application.js`
- Add `/app/javascript/packs/application.css`
- `rails assets:precompile`
- manifest.json includes compiled application.js only, application.css is omitted.
- Change application.css to any other file basename, repeat above steps, and manifest is created correctly.

This is minor and easy to add to documentation, but caused quite the headache as it took awhile to determine exactly what was happening here.

**Comment by jakeNiemiec** [comment] 2019-05-20 19:44
Dupe of https://github.com/rails/webpacker/issues/2088, it points to https://github.com/rails/webpacker/blob/master/package/environments/base.js#L65 as the source of the problem.

**Comment by rossta** [comment] 2021-01-13 01:37
Fixed by https://github.com/rails/webpacker/pull/2476

**Closed by rossta** 2021-01-13 01:37 UTC
