### ISSUE TITLE
PostCSS config file should be provided in loader

### ISSUE THREAD

**Issue by renchap** [rails/webpacker#1723] opened 2018-10-01 14:46 UTC
`postcss-loader`'s `options.config.path` has been removed since beta 2.

This breaks compilation when you import some CSS files from `node_modules`. For example I am getting:
```
ERROR in /home/xxx/www/xxx/shared/node_modules/react-calendar/dist/Calendar.css
Module build failed (from /home/xxx/www/xxx/shared/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from /home/xxx/www/xxx/shared/node_modules/postcss-loader/src/index.js):
Error: No PostCSS Config found in: /home/xxx/www/xxx/shared/node_modules/react-calendar/dist
```

This is fixed by providing the `config.path` option to the loaded.

There have been a few PR around this:
- https://github.com/rails/webpacker/pull/1676 tries to use the default `postcss.yml` when not present
- https://github.com/rails/webpacker/pull/1660 removed the config option

Ping @JakeLaCombe as you worked on this.

**Comment by aganov** [comment] 2018-10-01 20:34
The problem is that the `node_modules` directory is often **symlinked** with capistrano based deployment and `postcss` is seeking its config file for every import you've specified in your bundles. You can either copy `.postcssrc.yml` to `/var/www/app/shared/` during deployment, but this is a temporary **DIRTY** fix.

```ruby
execute :cp, File.join(release_path, ".postcssrc.yml"), shared_path
```

More cleaner solution would be to fetch postcss loader and set `config.path` option to it.

In your `config/webpack/environment.js`

```js
const path = require("path")
Object.assign(environment.loaders.get("css").use.find(el => el.loader === "postcss-loader").options, {
  config: {
    path: path.resolve(__dirname, "../..", ".postcssrc.yml")
  }
})
```

**Comment by JakeLaCombe** [comment] 2018-10-01 20:44
In my opinion, at that point I think you are better to use a straight up JSON object to store the postcss configuration as opposed to using a .postcssrc.yml file.

```
const postCssOptions = {
  ident: 'postcss',
  plugins() {
    return[
      Autoprefixer({ browsers:[
        'iOS >= 10',
        'last 2 and_chr versions',
        'last 2 android versions',
        'last 2 chrome versions',
        'last 2 edge versions',
        'last 2 firefox versions',
        'ie 11',
        'last 2 safari versions',
      ]})
    ];
  }
};

environment.loaders.forEach((loader) => {
   loader.value.use.forEach((use) => {
     if(use.loader == 'postcss-loader') {
       use.options = postCssOptions;
     }
   });
});
```

That could be a viable option as well.

**Comment by jpickwell** [comment] 2018-10-06 00:31
This is a problem when deploying with Capistrano. Another solution when setting the `config.path` option is:
```javascript
// modify all stylesheet loaders
['css', 'moduleCss', 'moduleSass', 'sass'].forEach((loaderName) => {
  // in Webpacker 4, postcss-loader is always 3rd
  const postcssLoaderUse = environment.loaders.get(loaderName).use[2]

  postcssLoaderUse.options.config = { path: path.resolve() }
})
```

`path.resolve` returns the current working directory when not passed any arguments ([docs](https://nodejs.org/api/path.html#path_path_resolve_paths)).
> If no path segments are passed, path.resolve() will return the absolute path of the current working directory.

The `postcss-loader` [readme](https://github.com/postcss/postcss-loader/tree/v3.0.0#config) states that you cannot change which file is used, only which directory to start from.
> Note that you can't use a filename other than the supported config formats (e.g .postcssrc.js, postcss.config.js), this option only allows you to manually specify the directory where config lookup should start from

Obviously, it would be better if this were set in the webpacker code.

**Comment by renchap** [comment] 2018-10-07 11:39
Nice catch, I did not knew this about the `config` option! Looks like it fixes the issue with a symlinked `node_module`

**Comment by lakim** [comment] 2018-11-29 14:34
Just had the same issue while deploying with capistrano which symlinks `node_modules`.

@jpickwell's PR https://github.com/rails/webpacker/pull/1738 would solve this issue without having to override the default config which is very cumbersome and fragile.
Would be great if we could merge it.

**Comment by danielpowell4** [comment] 2018-12-19 23:13
@gauravtiwari can close as #1738 has merged

Excited about rc!

**Closed** 2018-12-20 10:34 UTC
