### ISSUE TITLE
Babel 7 Support Release

### ISSUE THREAD

**Issue by jfangrad** [rails/webpacker#1714] opened 2018-09-26 17:06 UTC
Hey, I noticed that master has been updated to use Babel 7. Is there a timeline on releasing a new version with the Babel 7 included? I need babel 7 support to pull in a new module to one of my projects and can't do so until webpacker is updated.

If not would it be possible to do a pre-release version?

**Comment by swrobel** [comment] 2018-09-26 21:16
Duplicate of #1713

**Comment by gauravtiwari** [comment] 2018-10-01 07:58
Just made another pre-release:

```
yarn add @rails/webpacker@next
bundle update webpacker
```

**Closed by gauravtiwari** 2018-10-01 07:58 UTC

**Comment by Welziewagers2015** [comment] 2018-12-03 19:43
Just saw the release on the yarn add nice work you all.
