### ISSUE TITLE
Webpacker gem generates incorrect manifest.json on windows 10

### ISSUE THREAD

**Issue by cshupp1** [rails/webpacker#1174] opened 2018-01-12 18:22 UTC
I am using:
```
    webpacker (3.2.0)
    rails (5.1.4)
    JRuby 9.1.15.0
```

Suppose in /app/javascript/packs/hello I have:
```
hello_react.jsx
```

On Windows the manifest generated is:
```
{
  "application.js": "/packs/application-0dc18709a85406b5e3f5.js",
  "application.js.map": "/packs/application-0dc18709a85406b5e3f5.js.map",
  "hello\\hello_react.js": "/packs/hello\\hello_react-5a67faa5e91dd316f476.js",
  "hello\\hello_react.js.map": "/packs/hello\\hello_react-5a67faa5e91dd316f476.js.map"
}
```

This means in my erb file this does not work:
```
<%=javascript_pack_tag 'hello/hello_react'  %>
```

I must do this:
```
<%=javascript_pack_tag 'hello\hello_react'  %>
```
for a lookup to succeed.

Workaround:
```
class String
  def os_path!
      self.gsub!('/', java.io.File::separator)
      self.gsub!('\\', java.io.File::separator)
  end
end
```

in erb:

```
<%=javascript_pack_tag 'hello/hello_react'.os_path!  %>
```

**Comment by gauravtiwari** [comment] 2018-01-21 16:30
Thanks @cshupp1 for filing this. I don't have access to a windows machine so don't know what the problem is. If it's okay please could you take a look and submit a PR please?

**Comment by cshupp1** [comment] 2018-01-22 16:07
Will do.

**Comment by cshupp1** [comment] 2018-01-22 18:58
@gauravtiwari 
I have everything ready to go, all tests are passing.  My attempt to create a branch to make a pull request fails.

C:\work\VSO\webpacker\webpacker>git push
remote: Permission to rails/webpacker.git denied to cshupp1.
fatal: unable to access 'https://github.com/rails/webpacker/': The requested URL returned error: 403

Can you help?

Thanks,
Cris

**Comment by gauravtiwari** [comment] 2018-01-22 19:00
@cshupp1 Please fork webpacker repo and then make a PR using that repo. https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by cshupp1** [comment] 2018-01-22 19:28
@gauravtiwari thanks for that.  Submitted.

**Comment by guilleiguaran** [comment] 2018-01-22 20:13
This has been fixed in `webpack-manifest-plugin` https://github.com/danethurber/webpack-manifest-plugin/pull/78 but we need to wait for the final release of the plugin (currently the fix is available only in 2.0.0-rc.1)

Meanwhile you can use this as workaround in `config/webpack/environment.js`:

```javascript
// This is a temporary workaround for generating manifest.json on Windows. The problem is already fixed in //
// webpack-manifest-plugin 2.0.0-rc.1. Remove this piece of code when @rails/webpacker incorporates the new version
// of webpack-manifest-plugin.
const config = require('@rails/webpacker/package/config')
const ManifestPlugin = require('webpack-manifest-plugin')
environment.plugins.append('Manifest', new ManifestPlugin({
  publicPath: config.publicPath,
  writeToFileEmit: true,
  filter: f => {
    f.name = f.name.replace(/\\/g, '/')
    f.path = f.path.replace(/\\/g, '/')
    return f
  }
}))
```

You also might need to execute `ruby bin/yarn add webpack-manifest-plugin` so the require statement would work.

Reference: https://github.com/webpack-contrib/file-loader/issues/238#issuecomment-355282434

**Comment by cshupp1** [comment] 2018-01-22 20:22
I will try it.

**Comment by cshupp1** [comment] 2018-01-22 20:37
Old manifest.json:
```
{
  "application.js": "/packs/application-575da87a6250aec77b5c.js",
  "application.js.map": "/packs/application-575da87a6250aec77b5c.js.map",
  "components\\dialog\\dialog.js": "/packs/components\\dialog\\dialog-dc98902f9c0da9e4f1d2.js",
  "components\\dialog\\dialog.js.map": "/packs/components\\dialog\\dialog-dc98902f9c0da9e4f1d2.js.map",
  "images\\VA-header.js": "/packs/images\\VA-header-2c5f1ccfd84e5d9c50fa.js",
  "images\\VA-header.js.map": "/packs/images\\VA-header-2c5f1ccfd84e5d9c50fa.js.map",
  "packs\\images\\VA-header.png": "/packs/packs/images/VA-header-e6dc135efab88117c2a25c10c9b4e404.png",
  "stylesheets\\layout.css": "/packs/stylesheets\\layout-3eab067aa4651bbb371f1d9e9c2c1219.css",
  "stylesheets\\layout.css.map": "/packs/stylesheets\\layout-3eab067aa4651bbb371f1d9e9c2c1219.css.map",
  "stylesheets\\layout.js": "/packs/stylesheets\\layout-59f9834050ac2cc94447.js",
  "stylesheets\\layout.js.map": "/packs/stylesheets\\layout-59f9834050ac2cc94447.js.map"
}
```

New manifest.json:
```
{
  "application.js": "/packs/application-575da87a6250aec77b5c.js",
  "application.js.map": "/packs/application-575da87a6250aec77b5c.js.map",
  "components/dialog/dialog.js": "/packs/components/dialog/dialog-dc98902f9c0da9e4f1d2.js",
  "components/dialog/dialog.js.map": "/packs/components/dialog/dialog-dc98902f9c0da9e4f1d2.js.map",
  "images/VA-header.js": "/packs/images/VA-header-2c5f1ccfd84e5d9c50fa.js",
  "images/VA-header.js.map": "/packs/images/VA-header-2c5f1ccfd84e5d9c50fa.js.map",
  "packs/images/VA-header.png": "/packs/packs/images/VA-header-e6dc135efab88117c2a25c10c9b4e404.png",
  "stylesheets/layout.css": "/packs/stylesheets/layout-3eab067aa4651bbb371f1d9e9c2c1219.css",
  "stylesheets/layout.css.map": "/packs/stylesheets/layout-3eab067aa4651bbb371f1d9e9c2c1219.css.map",
  "stylesheets/layout.js": "/packs/stylesheets/layout-59f9834050ac2cc94447.js",
  "stylesheets/layout.js.map": "/packs/stylesheets/layout-59f9834050ac2cc94447.js.map"
}
```

This looks good!

**Comment by cshupp1** [comment] 2018-01-22 20:44
Whoops I wanted to leave this open until the dependency is mated with webpacker. I hope that is OK.

**Comment by guilleiguaran** [comment] 2018-01-22 20:45
@cshupp1 sure, let's keep this open until we upgrade `webpack-manifest-plugin`

**Comment by gauravtiwari** [comment] 2018-01-22 20:55
Ahh cool, thanks @guilleiguaran for the fix 👍

**Comment by gauravtiwari** [comment] 2018-12-15 13:56
Please try the latest RC, otherwise feel free to open a new issue with more details.

**Closed** 2018-12-15 13:56 UTC
