### ISSUE TITLE
Uncaught ReferenceError: ActiveStorage is not defined (when used with VueJS)

### ISSUE THREAD

**Issue by hovancik** [rails/webpacker#1246] opened 2018-02-04 16:15 UTC
Hi,  
not sure what I am doing wrong, but I have a pack `show.js`: 
```
import * as ActiveStorage from 'activestorage'
...
ActiveStorage.start()
```
And I'm getting `Uncaught ReferenceError: ActiveStorage is not defined`
In package.json I have: 

```
    "@rails/webpacker": "^3.0.2",
    "activestorage": "^0.1.1",
```
I can see `activestorage` in `node_modules` fine. Tried removing node_modules and yarn again, but no change.

**Comment by hovancik** [comment] 2018-02-06 09:01
So it seems to be something with using VueJS and ActiveStorage together: https://forum.vuejs.org/t/setting-up-activestorage-with-vuejs/27036

If anyone is using ActiveStorage with VueJS, I would love to see how to do it correcty

**Comment by gauravtiwari** [comment] 2018-04-02 19:20
@hovancik Closing this one, since this doesn't seem like an issue caused by Webpacker. Were you able to figure it out?

**Closed** 2018-04-02 19:20 UTC

**Comment by hovancik** [comment] 2018-04-03 06:14
Nope, I did not.

**Comment by gauravtiwari** [comment] 2018-04-03 08:08
@hovancik Add I see. Would make sense to post this on SO with code and see anyone got answers there.
