### ISSUE TITLE
Deployment fails with webpacker 5.2.1 when `additional_paths` is `nil`

### ISSUE THREAD

**Issue by brandonzylstra** [rails/webpacker#2706] opened 2020-08-22 02:37 UTC
The following commit causes deployment to fail

```
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -559,7 +559,7 @@ GEM
       nokogiri (~> 1.6)
       rubyzip (>= 1.3.0)
       selenium-webdriver (>= 3.0, < 4.0)
-    webpacker (5.1.1)
+    webpacker (5.2.1)
       activesupport (>= 5.2)
       rack-proxy (>= 0.6.1)
       railties (>= 5.2)
```

Here's the failure:
```
rake aborted!
NoMethodError: undefined method `+' for nil:NilClass
/var/www/rsp/shared/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker/configuration.rb:31:in `additional_paths'
/var/www/rsp/shared/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker/configuration.rb:35:in `additional_paths_globbed'
/var/www/rsp/shared/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker/compiler.rb:93:in `default_watched_paths'
/var/www/rsp/shared/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker/compiler.rb:57:in `watched_files_digest'
/var/www/rsp/shared/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker/compiler.rb:38:in `fresh?'
/var/www/rsp/shared/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker/compiler.rb:43:in `stale?'
/var/www/rsp/shared/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker/compiler.rb:22:in `compile'
/var/www/rsp/shared/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker/commands.rb:51:in `compile'
/var/www/rsp/shared/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker.rb:35:in `compile'
/var/www/rsp/shared/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/tasks/webpacker/compile.rake:23:in `block (4 levels) in <main>'
/var/www/rsp/shared/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker.rb:28:in `ensure_log_goes_to_stdout'
/var/www/rsp/shared/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/tasks/webpacker/compile.rake:22:in `block (3 levels) in <main>'
/var/www/rsp/shared/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/webpacker.rb:20:in `with_node_env'
/var/www/rsp/shared/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/tasks/webpacker/compile.rake:21:in `block (2 levels) in <main>'
/var/www/rsp/shared/bundle/ruby/2.6.0/gems/webpacker-5.2.1/lib/tasks/webpacker/compile.rake:14:in `block in enhance_assets_precompile'
/var/www/rsp/shared/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/app_rsp/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
/home/app_rsp/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
Tasks: TOP => webpacker:compile
(See full trace by running task with --trace)
```

Here's a diff between the previous working code and the current code:

```
--- a/webpacker-5.1.1/lib/webpacker/configuration.rb
+++ b/webpacker-5.2.1/lib/webpacker/configuration.rb
@@ -27,12 +27,13 @@ class Webpacker::Configuration
     globbed_path_with_extensions(source_path.relative_path_from(root_path))
   end

-  def resolved_paths
-    fetch(:resolved_paths)
+  def additional_paths
+    fetch(:additional_paths) + resolved_paths
   end

-  def resolved_paths_globbed
-    resolved_paths.map { |p| globbed_path_with_extensions(p) }
+  def additional_paths_globbed
+    additional_paths.map { |p| globbed_path_with_extensions(p) }
   end

   def source_entry_path
@@ -76,6 +77,14 @@ class Webpacker::Configuration
   end

   private
+    def resolved_paths
+      paths = data.fetch(:resolved_paths, [])
+
+      warn "The resolved_paths option has been deprecated. Use additional_paths instead." unless paths.empty?
+
+      paths
+    end
+
     def fetch(key)
       data.fetch(key, defaults[key])
     end
```

My initial work-around was to add this to my config:

```
additional_paths:
  - app/assets/images
```

But I'll try to send a PR later...

**Comment by joelvh** [comment] 2020-08-23 21:20
Duplicate of #2699

**Comment by emptyflask** [comment] 2020-11-03 21:17
:+1: 
Just ran into this and was about to fix it myself.

**Closed as completed** 2021-08-27 12:19 UTC
