### ISSUE TITLE
Can't get app to compile in a new Angular + Webpacker Application 

### ISSUE THREAD

**Issue by mayordwells** [rails/webpacker#2180] opened 2019-07-15 06:44 UTC
I have created a new Rails app and tried to add Angular to it but it fails to compile. I have tried different options from the documentation but I am getting the same error. 

<img width="1280" alt="Screen Shot 2019-07-15 at 9 38 24 AM" src="https://user-images.githubusercontent.com/1370340/61198868-72c86200-a6e4-11e9-9082-0bac7faf6b8c.png">

I have followed a few instructions from this issue - https://github.com/rails/webpacker/pull/2031

and followed the documentation from here - https://github.com/rails/webpacker/blob/master/docs/es6.md and here https://github.com/rails/webpacker#angular-with-typescript

But these did not fix anything. Installing Angular with Webpacker and starting the app is supposed to work by default, but it looks like the source of the problem is the new implementation of core-js. Any idea how to fix this?

I have pushed a demo app on github to demo this problem please take a look here - https://github.com/mayordwells/angular-webpacker-app

**Comment by CyHunterX** [comment] 2019-07-16 18:05
Well i have the same issue in the installation of angular with webpack in rails. I make a research for more than a month and i don't found nothing about it. So is a bug, or a line of code, i need to add some gem or add some plug in with yarn? i want to know how to set up this and work with angular and rails.

here i have a output 
![Screenshot from 2019-07-14 13-48-28](https://user-images.githubusercontent.com/7233396/61318240-9ff33e00-a7d2-11e9-935e-055bcb746b4a.png)

**Comment by ayazhussein** [comment] 2019-08-20 23:46
@mayordwells @CyHunterX 
if you are using core-js@3, you have to import "core-js/es/reflect" instead of "es6" and also "core-js/proposals/reflect-metadata" instead of "core-js/es7/reflect" or you can downgrade to core-js@2

**Comment by ibrahimab** [comment] 2019-09-13 22:19
I have confirmed that @ayazhussein's suggestion works.  For the people who want to know where to do this: app/javascript/<angular-app>/polyfills.ts

What I want to know is, why was rails 6 released with this major problem? @dhh
I would love to help solve this problem, if nobody is working on this. I am assuming not, because nobody is assigned to this issue, but would love confirmation from the core team.

**Comment by jakeNiemiec** [comment] 2019-09-13 22:55
> I would love to help solve this problem, if nobody is working on this.

Sure, a PR would be more than welcome! Here is the last time that file was changed: https://github.com/rails/webpacker/pull/736

> why was rails 6 released with this major problem?

I personally don't use angular anymore, so I rely on the community to send in PRs since these 3rd party libraries change often.

**Comment by ibrahimab** [comment] 2019-09-14 15:27
I have created a simple pull request, see #2286

**Comment by guillaumebriday** [comment] 2021-01-12 21:20
I think it's not relevant anymore, feel free to reopen if needed

**Closed by guillaumebriday** 2021-01-12 21:20 UTC
Labels: babel/coreJs
