### ISSUE TITLE
Rails erb loader Compile Error

### ISSUE THREAD

**Issue by andybluey** [rails/webpacker#1529] opened 2018-05-27 12:07 UTC
Hi All,

I've just included webpacker (inc erb support) to an existing project. I've moved code from the asset pipeline to the example in the docs 'hello_erb.js.erb'.

I can get `console.log('<%= image_tag "logo.svg" %>');` 

but not
`<% helpers = ActionView::Helpers::JavaScriptHelper %>
$('.class').html('<%= helpers.escape_javascript(@query) %>');`

With the error:
"Failed to compile.
./app/javascript/packs/hello_erb.js.erb
Module build failed: Error: rails-erb-loader failed with code: 1
    at ChildProcess.<anonymous> (/Users.../node_modules/rails-erb-loader/index.js:120:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
 @ multi (webpack)-dev-server/client?http://localhost:3035 ./app/javascript/packs/hello_erb.js.erb"

The error message isn't making it terribly easy to search further. 

I've also tried digging through some previous issues that might be related [https://github.com/rails/webpacker/issues/1256#issuecomment-367573638](url) and trying some different loader settings and file headings with no [luck.](https://github.com/usabilityhub/rails-erb-loader/issues/53)

Let me know if you need anymore info.

Thanks

webpacker '3.5'
rails '5.1.2'

**Comment by vill** [comment] 2018-05-28 03:18
I think the details should be looked for [here](https://github.com/usabilityhub/rails-erb-loader/issues/63).

**Comment by andybluey** [comment] 2018-05-28 04:48
Hi Vill, 

Thanks for getting back to me!

Sorry, just to confirm, should `DISABLE_SPRING=1 ./bin/webpack-dev-server` be included in the loader file - or run via console?

I did try both ways and also tried the rails console method but still getting the same error.

Thanks,
Andy

**Comment by vill** [comment] 2018-05-28 05:15
@andybluey, I think the issue is with `rails-erb-loader`. Possible solutions to the issue are taken from the [comment](https://github.com/usabilityhub/rails-erb-loader/issues/63#issuecomment-374791504) and the [issue](https://github.com/usabilityhub/rails-erb-loader/issues/47).

**Comment by Neilos** [comment] 2018-05-28 11:14
I ran into this issue (i.e. same error message) after running `rails webpacker:install:erb`. 

_rails-erb-loader_ **does** have an issue with poor error messages (see [here](https://github.com/usabilityhub/rails-erb-loader/issues/63)), which an obstacle to solving issues like this one, **but** the underlying issue may not be _rails-erb-loader_ itself. 

I'm using version 3.4.3 of webpacker, and the cause of this issue *for me* was that webpacker's example erb file _[hello_erb.js.erb](https://github.com/rails/webpacker/blob/v3.4.3/lib/install/examples/erb/hello_erb.js.erb)_ was not erb compilable.

The problem was in the javascript comment at the top of the file:
```ruby
// Run this example by adding <%= javascript_pack_tag 'hello_erb' %> to the head of your layout file
```

This has now been corrected in later versions of webpacker (and version 3.5 which is what @andybluey is using) to:
```ruby
// Run this example by adding <%%= javascript_pack_tag 'hello_erb' %> to the head of your layout file
```
Note the double `%%`.
I manually made this correction and it fixed the issue for me. 

**Although, my compilation issue and @andybluey 's issue aren't the same, I'm posting here, in case anyone else seeing the same message has similar compilation related problems**.

**Comment by luislezcair** [comment] 2018-06-07 18:13
I'm facing the same problem. erb-loader fails when there's a call to an asset helper like `asset_pack_path`. I've been struggling with this issue [here](https://github.com/usabilityhub/rails-erb-loader/issues/63#issuecomment-395485004).

**Comment by HorizonShadow** [comment] 2019-01-25 18:17
Just going to drop this here since it confounded me.

I was getting this error because the erb loader that webpacker:install:erb creates, has the following runner:

`runner: (/^win/.test(process.platform) ? 'ruby ' : '') + 'bin/rails runner'`

In my case, this was running a different version of ruby than I had set up for my rails project. Rails was expecting 2.4.5, and my system ruby was 2.5. 

Changing the line to specify the correct ruby install fixed the problem

`runner: (/^win/.test(process.platform) ? 'C:/Ruby24-x64/bin/ruby ' : '') + 'bin/rails runner'`

**Comment by guillaumebriday** [comment] 2020-08-25 07:20
Is this issue still relevant ?

Feel free to close it if not 👍

**Closed** 2021-01-12 20:18 UTC
