### ISSUE TITLE
NameError: uninitialized constant Mime

### ISSUE THREAD

**Issue by JimmyMow** [rails/webpacker#1313] opened 2018-03-02 18:03 UTC
When running `rails new my-app --webpack=react` I am getting the following:

```
...
rails  webpacker:install
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/msgpack-1.2.4/lib/msgpack/version.rb:2: warning: already initialized constant MessagePack::VERSION
/Users/jmow/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/msgpack-1.2.4/lib/msgpack/version.rb:2: warning: previous definition of VERSION was here
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/msgpack-1.2.4/lib/msgpack/msgpack.bundle: warning: already initialized constant MessagePack::ExtensionValue
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/msgpack-1.2.4/lib/msgpack.rb:22: warning: already initialized constant MessagePack::DefaultFactory
/Users/jmow/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/msgpack-1.2.4/lib/msgpack.rb:22: warning: previous definition of DefaultFactory was here
rails aborted!
NameError: uninitialized constant Mime
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/mime_type.rb:8:in `<main>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/parameters.rb:11:in `<module:Parameters>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/parameters.rb:5:in `<module:Http>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/parameters.rb:4:in `<module:ActionDispatch>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/parameters.rb:3:in `<main>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/request.rb:11:in `<main>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/actionpack-5.2.0.rc1/lib/action_dispatch/routing/route_set.rb:10:in `<main>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/engine.rb:535:in `routes'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/railtie.rb:190:in `public_send'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/railtie.rb:190:in `method_missing'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/engine.rb:385:in `isolate_namespace'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/activestorage-5.2.0.rc1/lib/active_storage/engine.rb:14:in `<class:Engine>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/activestorage-5.2.0.rc1/lib/active_storage/engine.rb:13:in `<module:ActiveStorage>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/activestorage-5.2.0.rc1/lib/active_storage/engine.rb:12:in `<main>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/all.rb:17:in `block in <main>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/all.rb:15:in `each'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/all.rb:15:in `<main>'
/Users/jmow/Projects/bolt/my-app/config/application.rb:3:in `<main>'
/Users/jmow/Projects/bolt/my-app/Rakefile:4:in `require_relative'
/Users/jmow/Projects/bolt/my-app/Rakefile:4:in `<main>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/command.rb:48:in `invoke'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/commands.rb:18:in `<main>'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
       rails  webpacker:install:react
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/msgpack-1.2.4/lib/msgpack/version.rb:2: warning: already initialized constant MessagePack::VERSION
/Users/jmow/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/msgpack-1.2.4/lib/msgpack/version.rb:2: warning: previous definition of VERSION was here
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/msgpack-1.2.4/lib/msgpack/msgpack.bundle: warning: already initialized constant MessagePack::ExtensionValue
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/msgpack-1.2.4/lib/msgpack.rb:22: warning: already initialized constant MessagePack::DefaultFactory
/Users/jmow/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/msgpack-1.2.4/lib/msgpack.rb:22: warning: previous definition of DefaultFactory was here
rails aborted!
NameError: uninitialized constant Mime
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/mime_type.rb:8:in `<main>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/parameters.rb:11:in `<module:Parameters>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/parameters.rb:5:in `<module:Http>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/parameters.rb:4:in `<module:ActionDispatch>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/parameters.rb:3:in `<main>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/actionpack-5.2.0.rc1/lib/action_dispatch/http/request.rb:11:in `<main>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/actionpack-5.2.0.rc1/lib/action_dispatch/routing/route_set.rb:10:in `<main>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/engine.rb:535:in `routes'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/railtie.rb:190:in `public_send'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/railtie.rb:190:in `method_missing'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/engine.rb:385:in `isolate_namespace'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/activestorage-5.2.0.rc1/lib/active_storage/engine.rb:14:in `<class:Engine>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/activestorage-5.2.0.rc1/lib/active_storage/engine.rb:13:in `<module:ActiveStorage>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/activestorage-5.2.0.rc1/lib/active_storage/engine.rb:12:in `<main>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/all.rb:17:in `block in <main>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/all.rb:15:in `each'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/all.rb:15:in `<main>'
/Users/jmow/Projects/bolt/my-app/config/application.rb:3:in `<main>'
/Users/jmow/Projects/bolt/my-app/Rakefile:4:in `require_relative'
/Users/jmow/Projects/bolt/my-app/Rakefile:4:in `<main>'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/command.rb:48:in `invoke'
/Users/jmow/.rvm/gems/ruby-2.5.0@global/gems/railties-5.2.0.rc1/lib/rails/commands.rb:18:in `<main>'
bin/rails:4:in `<main>'
...
```

**Comment by gauravtiwari** [comment] 2018-03-03 14:16
@JimmyMow Have you tried doing - `bundle update` and then run the installer again?

**Comment by gauravtiwari** [comment] 2018-03-20 17:28
Can't reproduce this locally, closing.... Feel free to reopen if this is still an issue.

**Closed by gauravtiwari** 2018-03-20 17:28 UTC
