### ISSUE TITLE
Sample Babel config for React breaks E2E testing with Headless Chrome on Heroku

### ISSUE THREAD

**Issue by phacks** [rails/webpacker#2578] opened 2020-05-11 12:16 UTC
This is a niche issue, but it’s one I struggled with for days and I feel like it’s worth sharing here (and possibly push a PR—more on that later).

On a new Rails/Webpacker app (`rails 6.0.2.1, webpacker 4.2.2`, React flavoured), I tried to setup an end-to-end test with Rspec, Capybara and Selenium for our Heroku CI.

The test requires JavaScript to work (the feature I’m testing is a modal using JQuery).

While the test was working perfectly on my local setup, I had a JavaScript error in the Headless Chrome running on Heroku:

```
SEVERE 2020-05-11 10:55:08 +0000: http://127.0.0.1:38842/packs-test/js/application-6f7c52381fdedefe0243.js 76:2892260 Uncaught TypeError: Cannot set property 'Rails' of undefined
```

After a long process of trial and error, I managed to pinpoint the issue on the React integration in the provided `babel.config.js`:

https://github.com/rails/webpacker/blob/22ab02b7c84e917f985ecc76f5916d144f43bfbf/lib/install/examples/react/babel.config.js#L20-L29

Specifically, if I remove the `@babel/react-preset` on L28, everything works perfectly on Heroku CI (and the error disappears).

I am fairly new to Rails and don’t have much experience with Babel, so I might be mistaken, but it looks like the fact that that line is also present in the following code block might be the cause of the issue:

https://github.com/rails/webpacker/blob/22ab02b7c84e917f985ecc76f5916d144f43bfbf/lib/install/examples/react/babel.config.js#L40-L46

All I know is that removing it fixed my issue.

Going forward, I am willing to create a pull request against this if you think that might be helpful. Creating a reproduction repo might be a bit of a hassle (as I need to setup Heroku, Heroku CI etc…) but if you need it to check the PR I can try and find the time.

Please tell me what works best for you!

**Comment by kpheasey** [comment] 2020-11-23 18:52
I ran into this after upgrade from webpacker 4.x to 5.x with Rails 5.2. I tried some other solutions related to corejs3, but removing the additional `@babel/preset-react` worked.

This issue was only seen on one application when 3 others were updated with no problem.  Additionally, the problem is only in our CI and does not happen in anyone's development environment.

**Comment by justin808** [comment] 2021-12-22 23:50
Hopefully resolved with v6.

**Closed by justin808** 2021-12-22 23:50 UTC
