### ISSUE TITLE
warning: conflicting chdir during another chdir block

### ISSUE THREAD

**Issue by n-rodriguez** [rails/webpacker#2801] opened 2020-12-05 14:31 UTC
Hi there!

Since [this change](https://github.com/rails/webpacker/commit/3760588534c54527d21c684c2cb5ca30cafc0901) I got this warning in CI :

```sh
/cache/nicolas/concerto/ruby-master/ruby/2.7.0/bundler/gems/webpacker-2d053ca996db/lib/webpacker/compiler.rb:56: warning: conflicting chdir during another chdir block
../cache/nicolas/concerto/ruby-master/ruby/2.7.0/bundler/gems/webpacker-2d053ca996db/lib/webpacker/compiler.rb:56: warning: conflicting chdir during another chdir block
/cache/nicolas/concerto/ruby-master/ruby/2.7.0/bundler/gems/webpacker-2d053ca996db/lib/webpacker/compiler.rb:56: warning: conflicting chdir during another chdir block
./cache/nicolas/concerto/ruby-master/ruby/2.7.0/bundler/gems/webpacker-2d053ca996db/lib/webpacker/compiler.rb:56: warning: conflicting chdir during another chdir block
../cache/nicolas/concerto/ruby-master/ruby/2.7.0/bundler/gems/webpacker-2d053ca996db/lib/webpacker/compiler.rb:56: warning: conflicting chdir during another chdir block
```

**Comment by ledermann** [comment] 2021-02-18 05:24
Much worse, with Ruby 3.0.0 this raises a RuntimeError:
https://github.com/ruby/ruby/pull/3591

In one of my apps this makes the test suite flaky - it fails sometimes, not every time. Still happens using `6.0.0.beta.5`

**Comment by n-rodriguez** [comment] 2021-03-06 03:59
See: https://github.com/rails/webpacker/pull/2788#issuecomment-791860416

**Comment by krists** [comment] 2021-03-07 18:46
@n-rodriguez @ledermann 

I had similar issues with flaky tests in CI due to parallel webpacker compile tasks.

A workaround for this is to pre-compile all assets before running feature/system tests and then disable compilation.
Only way how to achieve that is by changing `config/webpacker.yml` file.

Here is a rake task that does that:
```ruby
namespace :webpacker do
  desc "Change config/webpacker.yml compile parameter to false"
  task :disable_compile_in_test do
    config_path = Rails.root.join("config", "webpacker.yml")
    content = YAML.load(config_path.read)
    new_content = content.deep_merge({ "test" => { "compile" => false, "cache_manifest" => true } })
    new_yaml = YAML.dump(new_content, { line_width: -1 })
    config_path.write(new_yaml)
  end
end
```

And then CI test script should look something like this:
```yaml
- RAILS_ENV=test ./bin/rails assets:precompile webpacker:disable_compile_in_test
- ./bin/rails db:create db:structure:load
- ./bin/rails parallel:prepare parallel:spec
```

It would be great to achieve the same result with ENV variable or ERB support in `webpacker.yml` config file but at the moment it is not possible.

**Comment by fastloris** [comment] 2021-04-29 18:24
@n-rodriguez I took a look at the comment but don't understand exactly what I need to do to prevent this issue? I don't have any call to `asset_pack_path` in my app to remove.

**Comment by zealot128** [comment] 2021-05-04 09:43
Having the same problem, using Webpacker 6.0.0.beta6 + Ruby 3. Sporadically it will fail when tumbling over any image_pack_tag/asset_pack_tag. Server restart/spring stop seems to help. The workaround of precompilation is not very convenient for local development, where the tests also fail from time to time.

The other "workaround" of removing asset_pack_tag means, one can not use images together with Webpacker as described in the README, which is too bad.

Is there a chance to have the issue reopened? I feel, this will become much more present, when more user update to Ruby 3/ Webpacker 6 in the future.

**Comment by fesplugas** [comment] 2021-05-07 09:03
Same problem here. We have fixed it by applying @zealot128 patch.

**Comment by clinejj** [comment] 2021-06-30 19:23
@n-rodriguez is it possible to re-open this issue? I experienced this problem and was able to fix with @zealot128's patch, and I don't think it's reasonable to suggest people remove their `asset_pack_path` calls when that's recommended in the README (and a breaking change from previous versions). @kukunin suggested a thread-safe fix at https://github.com/rails/webpacker/pull/2788#issuecomment-863898053 that might be a better solution than the original PR.

**Comment by Willardgmoore** [comment] 2021-07-22 17:08
Looks like a real issue to me too. Disabling compile on our system test suite resolved this error for a member on our team. 

```2021-07-22 10:37:46 -0600 Rack app ("GET /notes/582398282" - (127.0.0.1)): #<ActionView::Template::Error: conflicting chdir during another chdir block>
[Screenshot Image]: /Users/admin/workspace/horizonpwr-rails/tmp/screenshots/failures_test_Mark_notifications_as_read_for_all_notifications_within_a_thread.png
E
Error:
NotificationsTest#test_Mark_notifications_as_read_for_all_notifications_within_a_thread:
ActionView::Template::Error: conflicting chdir during another chdir block
    app/views/layouts/application.html.erb:16
    lib/jumpstart/lib/jumpstart/account_middleware.rb:30:in `call'
rails test test/system/notifications_test.rb:14```

**Comment by mildred** [comment] 2021-09-29 16:22
I tracked this down and it was possible to avoid this error. I had the error during interactive use of the rails app in the development environment.

It was caused by the fact that webpack and webpacker had mismatching versions. it caused webpack to start the dev server on a different port than webpacker configured. Consequently, webpacker could not detect the server was running and tried to recompile from rails. Because rails is started with puma with multiple threads, when two threads tried to recompile at the same time, it caused the chdir issue.

The code that triggers the recompiling is here:

https://github.com/rails/webpacker/blob/master/lib/webpacker/manifest.rb#L22

In particular, if `compiling?` is false, rails will never try to recompile and the chdir error will never be triggered. You can look down in this file what's the implementation for `compiling?` but there are two ways to disable it:

- configure `compiling: false` in `config/webpacker.yml`
- make sure that a webpack dev server is running on the correct port number so that webpacker can find it and avoid compiling

You can debug it all with the rails console easily:

- `Webpacker::Instance.new.manifest.send(:compiling?)` should be false
- `Webpacker::Instance.new.config.compile?` should match the `compile` item in your webpacker configuration
- `Webpacker::Instance.new.config.dev_server.present?` should be true if you have the webpack-dev-server running
- `Socket.tcp(Webpacker::Instance.new.dev_server.host, Webpacker::Instance.new.dev_server.port, connect_timeout: 3).close` should not raise any exception if you have the webpack-dev-server running

**Comment by justin808** [comment] 2021-12-22 23:29
Does anybody have a PR to address this issue?

**Comment by aried3r** [comment] 2022-01-18 11:26
> Much worse, with Ruby 3.0.0 a RuntimeError is raised:
> [ruby/ruby#3591](https://github.com/ruby/ruby/pull/3591)

There's also https://github.com/ruby/ruby/pull/3990 which switched it back to a warning, but I'm also seeing the exception with Ruby 3.0.3. See also https://bugs.ruby-lang.org/issues/15661#note-15.

@justin808, isn't your own PR perhaps a fix for this? https://github.com/rails/webpacker/pull/3233

**Closed** 2022-01-19 12:31 UTC
Labels: bug
